### ISSUE TITLE
How to override default if mysite folder is renamed

### ISSUE THREAD

**Issue by g4b0** [briceburg/silverstripe-flexilink#2]
Please show in documentation how to override config settings. If mysite folder is renamend to something that comes alphabetically before flexyfield your example code does not work.

**Comment by briceburg** [comment]
This may be related to a missing 'After' entry in your site's YML config. I'll make a note in the docs to clarify. Have successfully tested with 'mysite' folder renamed to 'abc'. Here's an example where i add 'Google' to the field type selection;

**/abc/_config/config.yml**

``` yml
---
Name: abc
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'site'

FlexiLink:
  allowed_types:
    - Page
    - ExternalURL
    - YouTubeID
    - Google

FlexiLinkField:
  field_types:
    Page:
      field: TreeDropdownField
      description: Select a Page to Link To
    ExternalURL: 
      field: TextField
      description: URL to link to (include http:// ...)
    YouTubeID:
      field: TextField
      description: YouTube Video ID
    Google:
      field: TextField
      description: TestTest
```

Be sure to ?flush=all after updating configuration. YML configuration is cached by SilverStripe, and a flush must be issued when changes are made.

**Comment by g4b0** [comment]
I'm trying to remove YouTube from FlexiField through this dedicated YAML in abcmysite/_config folder:

``` YAML
---
Name: myflexilink
After:
  - 'framework/*'
  - 'cms/*'
---
FlexiLink:
  allowed_types:
    - Page
    - ExternalURL
```

The YouTubeId option is still there also after a flush=all. I also tried, without success:

``` YAML
---
Name: myflexilink
After: flexilink
---
FlexiLink:
  allowed_types:
    - Page
    - ExternalURL
```

The SS version is 3.1.5

**Comment by briceburg** [comment]
@g4b0 great catch! I've moved configuration entirely to the FlexiLinkField class and properly allow overriding. Please see the updated docs. You can hide YouTubeID with the following;

``` yml
FlexiLinkField:
  allowed_types:
    - Page
    - ExternalURL
```
